package workspace

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ownpulse/ownpulse-dev/src/config"
)

func TestGenerateSettings_NewFile(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".claude"), 0755); err != nil {
		t.Fatal(err)
	}

	if err := generateSettings(dir, false); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".claude", "settings.json"))
	if err != nil {
		t.Fatal(err)
	}

	var settings map[string]interface{}
	if err := json.Unmarshal(data, &settings); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}

	env, ok := settings["env"].(map[string]interface{})
	if !ok {
		t.Fatal("missing env key")
	}
	if env["CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"] != "1" {
		t.Errorf("teams flag = %v, want \"1\"", env["CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"])
	}
}

func TestGenerateSettings_MergesExisting(t *testing.T) {
	dir := t.TempDir()
	claudeDir := filepath.Join(dir, ".claude")
	if err := os.MkdirAll(claudeDir, 0755); err != nil {
		t.Fatal(err)
	}

	existing := `{
  "permissions": {"allow": ["Bash"]},
  "env": {"MY_VAR": "keep"}
}`
	if err := os.WriteFile(filepath.Join(claudeDir, "settings.json"), []byte(existing), 0644); err != nil {
		t.Fatal(err)
	}

	if err := generateSettings(dir, false); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(claudeDir, "settings.json"))
	if err != nil {
		t.Fatal(err)
	}

	var settings map[string]interface{}
	if err := json.Unmarshal(data, &settings); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}

	// Existing permissions preserved.
	perms, ok := settings["permissions"].(map[string]interface{})
	if !ok {
		t.Fatal("permissions key was clobbered")
	}
	if perms["allow"] == nil {
		t.Error("permissions.allow was clobbered")
	}

	// Existing env var preserved.
	env := settings["env"].(map[string]interface{})
	if env["MY_VAR"] != "keep" {
		t.Errorf("MY_VAR = %v, want \"keep\"", env["MY_VAR"])
	}

	// Teams flag added.
	if env["CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"] != "1" {
		t.Errorf("teams flag = %v, want \"1\"", env["CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"])
	}
}

func TestGenerateSettings_DryRun(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".claude"), 0755); err != nil {
		t.Fatal(err)
	}

	if err := generateSettings(dir, true); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(dir, ".claude", "settings.json")
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Error("dry run should not create the file")
	}
}

// testAgentsDir creates a temporary directory with agent .md files and returns its path.
func testAgentsDir(t *testing.T, agents ...string) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "agents")
	if err := os.MkdirAll(dir, 0755); err != nil {
		t.Fatal(err)
	}
	for _, name := range agents {
		if err := os.WriteFile(filepath.Join(dir, name+".md"), []byte("# "+name), 0644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func TestGenerateCLAUDEmd(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".claude"), 0755); err != nil {
		t.Fatal(err)
	}

	agentsDir := testAgentsDir(t, "rust-backend", "react-frontend", "code-review", "arch-review")

	cfg := &config.WorkspaceConfig{
		Repos: []config.RepoConfig{
			{Name: "app", Description: "Main app"},
			{Name: "infra", Description: "Infrastructure"},
		},
	}
	repo := config.RepoConfig{
		Name:   "app",
		Agents: []string{"rust-backend", "react-frontend"},
	}

	if err := generateCLAUDEmd(cfg, repo, dir, agentsDir, false); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	for _, want := range []string{
		"<!-- Generated by opdev setup",
		"- **app** — Main app",
		"- **infra** — Infrastructure",
		"- rust-backend",
		"- react-frontend",
		"gh-actions",
		"CI/CD",
		"## Hard Rules",
		"Everything is IaC",
		"Review before committing",
		"## Agent Teams",
		"### Workflow",
		"arch-review",
		"isolation: \"worktree\"",
		"define the API contract",
	} {
		if !strings.Contains(content, want) {
			t.Errorf("missing %q in CLAUDE.md", want)
		}
	}
}

func TestGenerateCLAUDEmd_CategoriesAgents(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".claude"), 0755); err != nil {
		t.Fatal(err)
	}

	agentsDir := testAgentsDir(t, "rust-backend", "code-review", "security-review")

	cfg := &config.WorkspaceConfig{
		Repos: []config.RepoConfig{
			{Name: "app", Description: "Main app"},
		},
	}
	repo := config.RepoConfig{
		Name:   "app",
		Agents: []string{"rust-backend", "code-review", "security-review"},
	}

	if err := generateCLAUDEmd(cfg, repo, dir, agentsDir, false); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(filepath.Join(dir, ".claude", "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	content := string(data)

	if !strings.Contains(content, "**Write agents**") {
		t.Error("missing write agents section")
	}
	if !strings.Contains(content, "**Review agents**") {
		t.Error("missing review agents section")
	}
}

func TestGenerateCLAUDEmd_Overwrites(t *testing.T) {
	dir := t.TempDir()
	claudeDir := filepath.Join(dir, ".claude")
	if err := os.MkdirAll(claudeDir, 0755); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(claudeDir, "CLAUDE.md")
	if err := os.WriteFile(path, []byte("old content"), 0644); err != nil {
		t.Fatal(err)
	}

	agentsDir := testAgentsDir(t)

	cfg := &config.WorkspaceConfig{
		Repos: []config.RepoConfig{{Name: "app", Description: "Main app"}},
	}
	repo := config.RepoConfig{Name: "app"}

	if err := generateCLAUDEmd(cfg, repo, dir, agentsDir, false); err != nil {
		t.Fatal(err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "old content") {
		t.Error("CLAUDE.md was not overwritten")
	}
	if !strings.Contains(string(data), "Generated by opdev setup") {
		t.Error("CLAUDE.md missing generated header")
	}
}

func TestGenerateCLAUDEmd_DryRun(t *testing.T) {
	dir := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, ".claude"), 0755); err != nil {
		t.Fatal(err)
	}

	agentsDir := testAgentsDir(t)

	cfg := &config.WorkspaceConfig{}
	repo := config.RepoConfig{Name: "app"}

	if err := generateCLAUDEmd(cfg, repo, dir, agentsDir, true); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(dir, ".claude", "CLAUDE.md")
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Error("dry run should not create the file")
	}
}
