name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          fetch-depth: 0  # needed for git describe in VERSION

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build release binaries
        run: |
          mkdir -p dist
          make release

      - name: Checksum
        run: |
          cd dist
          sha256sum opdev-* > checksums.txt
          cat checksums.txt

      - name: Create GitHub release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe  # v2
        with:
          files: |
            dist/opdev-*
            dist/checksums.txt
          generate_release_notes: true
          fail_on_unmatched_files: true
